apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "url-shortener.fullname" . }}-public
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.pathmatcher: PathRegexp
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-crowdsec@kubernetescrd
spec:
  rules:
    - host: {{ (.Values.ingress.hosts | first).host | replace ".lab" ".fr" }}
      http:
        paths:
          - path: /[^/]+
            pathType: ImplementationSpecific
            backend:
              service:
                name: url-shortener
                port:
                  number: 4567